/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",

    // Or if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#F5F7F9",
        primary: "#FFFFFF",
        accent: "#1B73EE",
        highlightlabel: "#E9ECEF",
        typographyprimary: "#1D1D1F",
        typographysecondary: "#000000B2",
        typographytertiary: "#414141E5",
        typographyforth: "#34C759",
        typographyfifth: "#FF3B30",
        typographyinversesecondary: "#FFFFFFB2",
        outlinesecondary: "#85858566",
        outlinetertiary: "#ADE6FF99",
        outlinewarning: "#F1B120",
        componentprimary: "#F8F7F7",
        componentsecondary: "#DBEDFF",
        componenttertiary: "#FFFFFF99",
        statedefaultprimary: "#6B6B6B",
        successprimary: "#34C759",
        buttontertiary: "#EEF5FF",
        typographydefault: "#6B6B6B",
        day_accent: "#303C77",
        dark_background: "#0C152C",
        dark_primary: "#0A1124CC",
        dark_highlightlabel: "#0E1834",
        dark_typographysecondary: "#D4D4D4",
        dark_typographytertiary: "#FFFFFFB8",
        dark_typographyfifth: "#FF3B30",
        dark_typographyinversesecondary: "#ADADAD",
        dark_typographydefault: "#6B6B6B",
        dark_typographyprimary: "#FFFFFF",
        dark_outlinesecondary: "#85858566",
        dark_outlinetertiary: "#518CFF66",
        dark_componentprimary: "#6D6868",
        dark_componentsecondary: "#F0F0F080",
        dark_componenttertiary: "#00000099",
        dark_buttontertiary: "#0A1124CC",
      },
      fontFamily: {
        bold: ["SF-Pro-Display-Bold", "sans-serif"],
        black: ["SF-Pro-Display-Black", "sans-serif"],
        heavy: ["SF-Pro-Display-Heavy", "sans-serif"],
        Light: ["SF-Pro-Display-Light", "sans-serif"],
        Medium: ["SF-Pro-Display-Medium", "sans-serif"],
        Regular: ["SF-Pro-Display-Regular", "sans-serif"],
        Semibold: ["SF-Pro-Display-Semibold", "sans-serif"],
        Thin: ["SF-Pro-Display-Thin", "sans-serif"],
        Ultralight: ["SF-Pro-Display-Ultralight", "sans-serif"],
        iconlight: ["Font_Awesome_6_Pro-Light-300", "sans-serif"],
        iconregular: ["Font_Awesome_6_Pro-Regular-400", "sans-serif"],
        iconsolid: ["Font_Awesome_6_Pro-Solid-900", "sans-serif"],
        iconthin: ["Font_Awesome_6_Pro-Thin-100", "sans-serif"],
      },
      backgroundImage: {
        "underway-popup": "url('../public/img/underway-bg.jpg')",
      },
      backgroundPosition: {
        "top-center": "top center",
      },
    },
  },
  plugins: [require("@tailwindcss/line-clamp")],
};
